#!/bin/bash

function bucket() {
  echo reserved for future use
  # Create bucket and make objects publically downloadable
  #  gsutil mb "gs://${2}"
  #  gsutil defacl set public-read "gs://${2}"
}

function db() {
  gcloud sql instances create $1 \
    `# Not HA` \
    --availability-type zonal \
    --database-version POSTGRES_13 \
    --region $2 \
    --root-password $3 \
    --storage-auto-increase \
    --storage-size 10 \
    --storage-type SSD \
    --tier db-f1-micro
}

function help() {
  echo Command to create GCS bucket and Cloud sql db.
  echo ./create_gc_infra bucket [your bucket name]
  echo ./create_gc_infra db [instance name] [region] [root password]
}

# This command executes help function by default
"${@:-help}"