#!/bin/bash

# todo can I do this in same file this is called?

function start() {
  if [[ ! -f ~/cloud_sql_proxy ]]; then
    echo Downloading google cloud sql proxy
    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O ~/cloud_sql_proxy
    chmod +x ~/cloud_sql_proxy
  fi
  sudo mkdir -p /cloudsql
  sudo chown $USER:$USER /cloudsql
  nohup ~/cloud_sql_proxy -instances="$PROJECT_ID:$REGION:$POSTGRES_INSTANCE" -dir=/cloudsql &
  echo "cloud_sql_proxy started at PID $!"
  sleep 5 # Wait or psql may be unable to connect immediately
}

function stop() {
  kill "$(ps ax | grep "instances=$PROJECT_ID:$REGION:$POSTGRES_INSTANCE" | head -n1 | awk '{print $1;}')"
}

function help() {
  echo Start and stop proxy
  printf "\n"
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | cat -n
}

# This command executes help function by default
"${@:-help}"