# Generated by Django 3.2 on 2021-05-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_civicarea_civicpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="civicarea",
            name="slug",
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="civicpoint",
            name="slug",
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
