# Generated by Django 3.2 on 2021-05-26 12:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_civicpoint_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("title", models.TextField(help_text="Full description of issue")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Latitude and longitude of issue", srid=4326
                    ),
                ),
            ],
        ),
    ]
