# Generated by Django 3.2 on 2021-06-28 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_issue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("slug", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="tag_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                db_index=True,
                default=[],
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="tags",
            field=models.ManyToManyField(to="app.Tag"),
        ),
    ]
