# Generated by Django 3.2 on 2022-02-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_issue_tag_slugs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
