name: docker-compose-actions-workflow
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Init
        run: ./run init
      - name: Run all checks
        run: ./run checkall
#      - name: Run Integration tests in Django
#        run: docker-compose exec -T webdev /code/venv/bin/python3 /code/backend/manage.py test app --keepdb